#! /usr/bin/env sh
rm -r _build/prod
cd assets && ./node_modules/brunch/bin/brunch b -p && cd .. && MIX_ENV=prod mix do phx.digest, release --env=prod
cd _build/prod/rel/
rm nsg_notifier/releases/0.0.1/nsg_notifier.tar.gz
tar -czf nsg_notifier.tar.gz nsg_notifier
